# trigger:
#   branches:
#     include:
#       - main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.10.3'
  azureRmResourceGroup: 'automating-stuff-rg'
  azureRmStorageAccountName: 'automatingstuffsairaj'
  azureRmContainerName: 'tfstate'
  azureRmStateKey: 'terraform.tfstate'
  buildConfiguration: 'Release'

stages:
 - stage: Build
   displayName: 'Build the application'

   jobs:
   - job: BuildandPublish
     displayName: 'Build and Publish'
     steps:
     - checkout: self
     
     - task: UseDotNet@2
       inputs:
        version: '8.x'

     - task: NuGetAuthenticate@1
    
     - task: DotNetCoreCLI@2
       inputs:
        command: 'restore'
        projects: '**/*.csproj'    #'$(System.DefaultWorkingDirectory)/*.csproj'
        feedsToUse: 'select'

     - task: DotNetCoreCLI@2
       displayName: Build Application
       inputs:
         command: 'build'
         projects: '**/*.csproj'
         arguments: '--configuration $(buildConfiguration)'

      
     - task: DotNetCoreCLI@2
       displayName: '.NET Publish'
       inputs:
        command: 'publish'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

     - task: PublishPipelineArtifact@1
       displayName: 'Publish Artifact'
       inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'dotnet-application'
        publishLocation: 'pipeline'
